### ISSUE TITLE
How to render metadata other than title and subtitle

### ISSUE THREAD

**Issue by christiansakai** [martijnversluis/ChordSheetJS#100]
I tried to add other metadata such as `key` and also to name the verse, but it seems it is not rendered.

Example song

```
{title: Let it be}
{subtitle: ChordSheetJS example version}
{key: C}

{start_of_verse: Verse 1}
Let it [Am]be, let it [C/G]be, let it [F]be, let it [C]be
{end_of_verse}

{start_of_chorus}
[C]Whisper words of [G]wisdom, let it [F]be [C/E] [Dm] [C]
{end_of_chorus}
```

**Comment by martijnversluis** [comment]
Hey @christiansakai. Sorry for replying this late.

By default the formatters do not render metadata other than title and subtitle, because it depends on you use case what data should be rendered.

However, you can take a look at the different formatters (https://github.com/martijnversluis/ChordSheetJS/tree/master/src/formatter) for some inspiration and create your own based on the source code. When you parse a song, ‘song.metaData’ is an object containing all metadata.

Please let me know if this is helpful.

**Comment by christiansakai** [comment]
Thanks @martijnversluis that makes sense! Thanks for the amazing library!
