### ISSUE TITLE
How to detect the current key?

### ISSUE THREAD

**Issue by gpr19** [martijnversluis/ChordSheetJS#1066]
Is there any way to detect which key a song is in?

**Comment by martijnversluis** [comment]
Hey @gpr19. Thanks for reaching out.

Unless the current key is set in the song (either in chordpro or programmatically), there is no way to get the song key. 

You could probably implement something to guess the song key, but it is not a current or planned feature.

**Comment by edwinzap** [comment]
Few years ago I wrote my own chordpro library in which I implemented a basic key guesser system. I plan to join the development of this library since it looks great now. 

There are techniques like checking the first and last chord of the song, taking the most use chord,... 

I will try to implement that in the future (when I have more time).

**Comment by martijnversluis** [comment]
Wow, sounds great @edwinzap! Looking forward to your contributions, and thanks for reaching out! 👍
