### ISSUE TITLE
Erro 'null' 

### ISSUE THREAD

**Issue by gpr19** [martijnversluis/ChordSheetJS#1163]
I'm having an error in this new version, before I was using 9.0.0. This week I started a new project to test with the latest version (9.0.1).

When the enter key shows 'null'

Version 9.0.1: 
![image](https://github.com/martijnversluis/ChordSheetJS/assets/98890138/5d53b821-af77-4427-bae3-82bed68af27c)

But in version 9.0.0 works fine: 
![image](https://github.com/martijnversluis/ChordSheetJS/assets/98890138/cd226f19-9c59-47a8-8b6b-f23e5e579c54)

**Comment by martijnversluis** [comment]
Hey @gpr19. Thanks for reaching out! 

Could you elaborate on the code that is used to render the sheet? It would be nice to have the minimal bit of code that breaks on 9.0.1 or returns a different result.

**Comment by ldelia** [comment]
I'm experiencing this issue, for example, with this setup:
- Parser: ChordsOverWordsParser
- Formatter: HtmlTableFormatter
- Sheet:

```javascript

const sheet = `  F                      Am          Dm                Gm   C
Tonight I’m gonna have myself a real good time, I feel alive
        F           F7              Bb           Gm7                D7
And the world, I'll turn it inside out yeah, I'm floating around in ecstasy
   Gm    F    C  Gm   Gm    F    C
So don’t stop me now, don’t stop me
          Gm       F/G  Gm7   C         Dm7/C  C7
Cause I’m having a good time, having a  good   time

`;
```

The last empty line will produce a null being displayed, as you can see in this image:

![image](https://github.com/martijnversluis/ChordSheetJS/assets/1646735/362de49d-878e-47ff-8b59-3e7e338c522a)

This could be fixed by the client that is using the ChordSheetJS library by just trimming the sheet, but it would be great if the library could handle this scenario by itself.

**Comment by ldelia** [comment]
The same happens when two or more line breaks appear together in the middle of the sheet.

Here is the fix that I'm using before calling the ChordsOverWordsParser class:

`phraseToParse = phraseToParse.replace(/\n\n/g, '\n').trim();`

Does it make sense to include the fix in the ChordsOverWordsParser parser method?

**Comment by martijnversluis** [comment]
@gpr19 I think if found the issue, and I merged a fix. Will try to publish it soon 👍
