### ISSUE TITLE
Handle multiple chords on the same syllable

### ISSUE THREAD

**Issue by hlobit** [martijnversluis/ChordSheetJS#133]
To begin with, thank you for this beautiful piece of software.

I was just playing on ChordFiddle [here](https://martijnversluis.github.io/ChordFiddle/#chord_sheet=N4FwliA2CmBcAEAZaJ4XgI2gXwFDAGcBXDcKOeAYQAsB7AJwBMBla6FAKWfmgA8BDALYAHGPABu0egTC0AdnmA0GRAnlwBtAIIBdDQCE9lHQFkikcNp2joQA&preview=html), and I have to encode a song where a single syllable is long enough to be covered by multiple chords.

```chordpro
[A][B][C]Multi[A]ple
```

I finally handled it this way to make it readable:

```chordpro
[A]Mu [B]--- [C]- lti[A]ple
```

Is there something that can be done in the library to make this (edge?) case handled ? It seems to me a bit difficult, because it'd be needed to make chordsheetjs kind of syllable-aware...

**Comment by martijnversluis** [comment]
Hi @hlobit. Thanks for reaching out and for using ChordSheetJS!

Handling this issue is quite difficult indeed. The way I usually solve this issue, I borrowed from how it's usually done for sheet music. You can either repeat the syllable, separated by dashes, or use only dashes:

```
[A]Mu-[B]u-[C]ulti[A]ple
```
[(view on ChordFiddle)](https://martijnversluis.github.io/ChordFiddle/#chord_sheet=NoQQugsgrgtMBCZbAMJIDYBcCWowAd0BTIA&preview=html)

or:

```
[A]Mu-[B] - [C] - lti[A]ple
```
[(view on ChordFiddle)](https://martijnversluis.github.io/ChordFiddle/#chord_sheet=NoQQugsgrgtMBCYAEMnAMLNQGwC4EtQwAHbAUyA&preview=html)

There are still major parts from the ChordPro standard that need to be implemented in ChordSheetJS, so I'll probably not be able to solve issues that go beyond the standard very soon. Does this solve your problem though? Please let me know!
