### ISSUE TITLE
Directive values parsed as `[object Object]` in 10.7.0 and later

### ISSUE THREAD

**Issue by bkeepers** [martijnversluis/ChordSheetJS#1491]
Since 10.7.0, any directive with a value (e.g. `{title: Let It Be}`) gets parsed as the string `"[object Object]"`. I thought maybe it was just an issue with the custom formatter I wrote, but upon further inspection, the value of the tag is stored as that string.

I'm able to duplicate the issue by updating [ChordFiddle](https://github.com/martijnversluis/ChordFiddle) to 10.7.0 as well:

<img width="1582" alt="Screenshot 2024-12-04 at 9 58 19 PM" src="https://github.com/user-attachments/assets/b758fa5f-591d-4d26-bbf2-c2bfdcccce62">

**Comment by martijnversluis** [comment]
@bkeepers Thanks for reporting this. Unfortunately Parcel's caching has messed up quite some releases, as it appears not all updates actually ended up in the compiled bundles.

I just released `10.9.2` that should hopefully contain all updates that were missing since `10.7.0`. Can you try and see if parsing works correctly with that version?

**Comment by SamuMazzi** [comment]
If it can help I had the same problem and it works for me now!

**Comment by bkeepers** [comment]
@martijnversluis yes, that fixes it! Thanks!

> Unfortunately Parcel's caching has messed up quite some releases, as it appears not all updates actually ended up in the compiled bundles.

I'd be happy to work on a PR that replaces Parcel with [vite](https://vite.dev) or [esbuild](https://esbuild.github.io) if you're interested.
