### ISSUE TITLE
formatter is breaking lines

### ISSUE THREAD

**Issue by ashish-ch-98** [martijnversluis/ChordSheetJS#178]
I am building a song library using gatsby. In my project, I have used a combination of ChordJs and ChordsheetJs. I am writing all the lyrics with chords in a Markdown file. Until now the output of a ChordPro sheet was as defined in the docs, but since last week I am experiencing a bug on adding a new lyrics MD file to the project. 

To parse the file I use:
`const [song] = useState(new ChordSheetJS.ChordProParser().parse(post.internal.content))`

and to render the html output:
`const htmlChordSheet = new ChordSheetJS.HtmlDivFormatter().format(song)`

while using the `HtmlDivFormatter()` the HTML on the webpage now looks like this
<img width="229" alt="divformatter" src="https://user-images.githubusercontent.com/67867311/92157262-d0b78c00-ee47-11ea-9a3f-0eba94061a06.PNG">

I tried replacing `HtmlDivFormatter()` with `HtmlTableFormatter()`, this solved the issue but raised another one. The spacing between paragraphs was no longer there. 
The highlited area shows the end of a paragraph.
<img width="363" alt="tableformatter" src="https://user-images.githubusercontent.com/67867311/92157926-c944b280-ee48-11ea-943b-40db8b0075f1.PNG">

There is also issue with the regular chord sheet. On the webpage, chords move forward from their defined postion. 

Expected output
<img width="296" alt="expected_regular-sheets" src="https://user-images.githubusercontent.com/67867311/92158752-0493b100-ee4a-11ea-8274-bec0b12d858e.PNG">

output on webpage
<img width="310" alt="output-on-page" src="https://user-images.githubusercontent.com/67867311/92158842-24c37000-ee4a-11ea-8c0f-c757ca6bc919.PNG">

**Comment by martijnversluis** [comment]
Hi @ashish-ch-98, thanks for your question. 

What I probably could document better, is that the formatters do not add any styling, nor inline nor as a separate stylesheet. It only generates the HTML that would, with the proper default or custom CSS will correctly render the chord sheet. This is because ChordSheetJS is not aware of in which kind of application the sheet is being rendered.  for the styling it's 

I'll put an issue on the board to come up with some way to generate CSS for the chord sheet. For now, could you try using text-align to fix the chord alignment?

**Comment by martijnversluis** [comment]
Feature planned in #184
