### ISSUE TITLE
European notation support

### ISSUE THREAD

**Issue by mgiacopu** [martijnversluis/ChordSheetJS#401]
Hi! Thanks for your work.

I was wondering if you were planning to introduce support to the European notation (DO, RE, MI, FA, SOL, LA, SI).
To my knowledge this isn't yet a feature of this library.

Do you think this is feasible?

I could make a pull request and implement it myself if needed, but I think I'm going to require some tips on which files to modify.

**Comment by martijnversluis** [comment]
Hey @mgiacopu 

Thanks for submitting your issue and for offering your help! 

I'm currently finishing quite a thorough refactor that should make this feature easier to implement: #391. When that PR is merged, changes are required in the `Chord` and `Key` classes to make this work. You may want to watch that PR in order to be notified when it's merged.

Please reach out if you need more info at that time.

**Comment by mgiacopu** [comment]
Hi @martijnversluis

I've seen that #391 has been merged.
I was trying to setup the repo on my machine in order to start developing this feature, but I'm having quite an hard time getting it up and running.

What should the setup look like?

**Comment by martijnversluis** [comment]
Hey @mgiacopu. Thanks for asking, I realised there is no contribution guide in the README. The requirements to get started are as follows:

- you need NodeJS running on your system, version 14 or higher. If assume you already have that running, but if you don't installation instructions are [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
- you need to have Yarn installed, this is an alternative to NPM. Instructions are [here](https://classic.yarnpkg.com/lang/en/docs/install/)
- you need to have Git installed. If you don't, you can download it [here](https://git-scm.com/downloads)
- download the source code using `git clone https://github.com/martijnversluis/ChordSheetJS.git` or `git clone git@github.com:martijnversluis/ChordSheetJS.git` ([more info on which one to use](https://docs.github.com/articles/which-remote-url-should-i-use))
- the `src/` folder contains the actual code, the `test/` folder contains the tests that check the working of the code
- if you have made changes you can run `yarn test` to check.

Please reach out with more info about your system if you need more details, because installation differs greatly among operating systems, version managers etc.

**Comment by mgiacopu** [comment]
Hi @martijnversluis

I think I explained myself wrongly.
What i meant was like having a local installation of the package: I know something similar can be achieved using `npm link` but as I said I'm finding it tricky.

Besides that, I've started watching the code. In addition to changing `Chord` and `Key` I think also `Note` should be modified.

Maybe adding another constant other than `SYMBOL` and `NUMERIC` (something like `LATIN`) and then adding specific behavior to the new type of note or perhaps leveraging on the logic behind `NUMERIC`?
