### ISSUE TITLE
Putting a chord in the middle of a word adds an extra space

### ISSUE THREAD

**Issue by chrismaes87** [martijnversluis/ChordSheetJS#52]
Putting a chord in the middle of a word adds an extra space. This should not happen. See example below (wisdom is cut in two).

![screenshot from 2018-05-21 14-48-26](https://user-images.githubusercontent.com/6972561/40308391-6b313b58-5d06-11e8-8a01-3e3cc7f80ceb.png)

**Comment by martijnversluis** [comment]
@chrismaes87 I just released patch version [`2.4.4`](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v2.4.4) that fixes the bug. Please let me know if this solves your problem.

**Comment by chrismaes87** [comment]
@martijnversluis yes the problem is solved, only you introduced a new bug; you are now eating the space between words: 
![screenshot from 2018-05-26 13-49-08](https://user-images.githubusercontent.com/6972561/40575794-c0b3baf4-60eb-11e8-98c3-721ba0eded35.png)

**Comment by martijnversluis** [comment]
@chrismaes87 How are you parsing or building up the song that is formatted? As you can see in the [this example on ChordFiddle](https://martijnversluis.github.io/ChordFiddle/#chord_sheet=NoYQug6gFglgzgBwKYCcAEB3A9igJnNLAMzWADEwN5gBxMXLAWyA&preview=html) parsing and formatting a ChordPro song should work fine. 

However, it is important to tweak the CSS `white-space` property for the node in which the song is rendered, because otherwise browsers will ignore the trailing space. For ChordFiddle I am using:

```css
white-space: pre;
```

Another option would be to replace all spaces with non-breaking spaces (`&nbsp;`) after formatting the song.

Please let me know if this fixes your issue.

**Comment by typekpb** [comment]
@martijnversluis for me it did. Would you add it to docs in case others face the issue as well?
