### ISSUE TITLE
can't explain HtmlDivParser parsing

### ISSUE THREAD

**Issue by paulrobertpine** [martijnversluis/ChordSheetJS#520]
Hi Martin, 

Here is my code base: https://github.com/paulrobertpine/songbook-2022

For some of the songs, it parses like I'd expect (example: https://songbook-new.netlify.app/a-penny-more/) and for others (https://songbook-new.netlify.app/baby-one-more-time/), it adds extra paragraphs and I'm not sure why. The MarkDown looks the same and I can't see any special characters. 

Thanks, 
Paul

**Comment by martijnversluis** [comment]
Hey @paulrobertpine 

Sorry for delay, it took me some time to get around the issue. 

It turns out `baby-one-more-time.md` contains CRLF (Windows) line endings, while `a-penny-more.md` contains LF (Unix) line endings. When setting both to LF they render correctly.

I'll think about whether it should be `ChordSheetJS`'s responsibility to check and/or correct line endings.

To fix your issue you could use a package like this to fix the line endings: https://github.com/iShafayet/line-ending-corrector

**Comment by paulrobertpine** [comment]
Thank you, thank you!
