### ISSUE TITLE
Adding section class to words ending with colon

### ISSUE THREAD

**Issue by filipblaauw** [martijnversluis/ChordSheetJS#54]
In a application I'm developing, I wanted to style certain parts of the chord sheet with addinional css. For example, if I'm writing:
`Verse 1:`
I wanted to recognize this as a class of `section` (in this example with a bold text property).

Resulting in this parsed sheet:

**Verse 1:**
This is my lyrics for verse one.

I'm using the table formatter, so for now I have this regex checking for words ending in colon, or colon followed by any number of whitespaces in `html_table_formatter.js`:
```
key: 'cell',
    value: function cell(cssClass, value) {
      // If word ends with colon (with or without whitespaces), add section class to td:
      const regex = /:\s*$/;
      if (regex.test(value)) {
        return '<td class="section">' + (0, _html_entities_encode2.default)(value) + '</td>';
      }
      // Else return original string value
      return '<td class="' + cssClass + '">' + (0, _html_entities_encode2.default)(value) + '</td>';
    }
```

Downside of this, is of course if any part of the lyrics itself contains colon and printing this as bold. You may have a better solution.

I also thought of checking for specific words like `intro, verse, chorus, bridge, etc` - but it would be a long list of possible section names.

Any inputs on this, or maybe it could be offered as a feature?

**Comment by martijnversluis** [comment]
@filipblaauw Thanks for your question.

Important to know is whether or not you're using ChordPro as the source chord sheet. When using chord pro, you can use comment tags for this. See this [example on ChordFiddle](https://martijnversluis.github.io/ChordFiddle/#chord_sheet=N4Yw9gthCmB2AuAuABAYQBZgE4FcDOiAvgFDEDaAggLoAq6Alnso8vOtMmQCJUbb6lQkGAhQAhLPQAmAc2hFSZAOK0GTFmw7cqE6XKA&preview=html). The comments are rendered as `<td class="comment">`.

Another option is to create your own formatter that inherits from `HtmlTableFormatters` and override [this method](https://github.com/martijnversluis/ChordSheetJS/blob/master/src/formatter/html_table_formatter.js#L15). I do recommend you to use ES6 for that, because the compiled JavaScript is not that easy to read. You would write something like:

```js
class MyFormatter extends HtmlTableFormatter {
  outputPair(chords, lyrics) {
    const regex = /:\s*$/;
    const lyricsClass = (regex.test(lyrics) ? 'section' : 'lyrics');

    this.chordsLine += this.cell('chord', chords);
    this.lyricsLine += this.cell(lyricsClass, lyrics);
  }
}
```

Please let me know if you have any further question or need help.

**Comment by filipblaauw** [comment]
Thanks for giving such clear example, I'll have a go and test it out. I do use ChordPro as source, so I think extending the formatter seems like a good option, and easier to read as well :)
