### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by edertaveira** [martijnversluis/ChordSheetJS#762]
I'm trying to use the library on React Native, but I am just faced with this issue. 
When I import the ChordSheetJs in the component, it happens.

**Comment by martijnversluis** [comment]
Hey @edertaveira. Do you by chance have the corresponding stack trace?

What browser are you using? A Google search points out not all browsers support all RegExp features. That might require you to add some kind of plugin that adds the support, such as https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex (if you use Babel)

**Comment by perivar** [comment]
Really good library which I have used in the IOS app "ChordMaster Community". I also have the same issue and cannot use any of the latest versions The last working version with Expo and React Native is "chordsheetjs": "7.7.0". I tried to configure the babel plugin but got the same error message, so I gave up and reverted back to the version mentioned above.

**Comment by martijnversluis** [comment]
Thank you for this extra info, @perivar. I'll check the changes between `7.7.0 and the latest version. I suspect it has something to do with regex named match groups.

**Comment by perivar** [comment]
I am unable to find a stack trace in react native. The reason seem to be look behind https://stackoverflow.com/questions/56990784/no-stack-reason-unhandled-js-exception-invalid-regular-expression-invalid and https://github.com/facebook/react-native/issues/31767

**Comment by martijnversluis** [comment]
So far I haven't been able to find the cause. 

@edertaveira Is your project perhaps on Github, so I could try to run it locally and reproduce the error?

**Comment by edertaveira** [comment]
@martijnversluis sorry delay bro! 
So I switched to chordjs and I create a little parse using it. But I can create another project here to check it.

**Comment by perivar** [comment]
I have found the error, but I do not know how to fix it!
The issue is that expo / react native does not support lookbehind, and you added a positive lookbehind in the file chords_over_words_grammar.pegjs. 
The offending line is:
const secondWordPosition = pairLyrics.search(/(?<=\s+)\S/);

I just tested in a live expo app to change this regex in the node_modules/chordsheetjs/lib/index.js file to pairLyrics.search(/(\s+)\S/); 
and the error disappeared. (But of course the regex doesnt work properly since I dont know what it should be).

Can you please change from using a lookbehind to an alternative way?
See also here https://stackoverflow.com/questions/62087908/regex-invalid-group-specifier-name-react-native


Best Regards
Per Ivar

**Comment by martijnversluis** [comment]
Hey @perivar 

Thanks, that is very useful info to have! I’ve put this issue on the board and will try to find some time to resolve it.

**Comment by martijnversluis** [comment]
Hey @edertaveira @perivar I released `7.12.1` that should fix this error. Could you guys let me know if the issue is really gone?

**Comment by perivar** [comment]
> Hey @edertaveira @perivar I released `7.12.1` that should fix this error. Could you guys let me know if the issue is really gone?

Hi martijn, I can confirm that the error has disappeared :) Thanx.
